/testConfig/enable_verbose false
/run/initialize 
#
/process/activate Scintillation
/process/optical/scintillation/verbose 0
/process/optical/scintillation/setStackPhotons true
/process/optical/scintillation/setTrackSecondariesFirst true
#
# the Cerenkov process is needed even when we run on GPU (to get the number of photons to be produced) but we don't put optical photons on the stack
#
/process/activate  Cerenkov 
/process/optical/cerenkov/verbose 0
/process/optical/cerenkov/setStackPhotons true
/process/optical/cerenkov/setTrackSecondariesFirst true
#
/process/optical/rayleigh/verbose 0
/process/optical/absorption/verbose 0
/process/optical/boundary/verbose 0
#
/process/activate OpAbsorption
/process/activate OpRayleigh
/process/activate OpBoundary
/process/activate OpMieHG
#
/run/initialize 
/random/setSeeds 7 38 
/testConfig/FileName NewHitsG4.root
/testConfig/writeHits true
/testConfig/enable_opticks false
/gun/particle mu+
/gun/energy 1. GeV
/gun/position 0. 0. 0.
/gun/direction 0. 0. 1.
/run/beamOn 5
